# Generated by Django 3.1.1 on 2020-10-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceapp', '0002_quizdb_live'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizdb_live',
            name='img_bool',
        ),
        migrations.AlterField(
            model_name='quizdb_live',
            name='img',
            field=models.ImageField(default='None', upload_to='QuizImages'),
        ),
    ]
