# Generated by Django 3.1.1 on 2020-10-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceapp', '0003_auto_20201002_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizdb_live',
            name='img_bool',
            field=models.BooleanField(default=False),
        ),
    ]
