# Generated by Django 3.1.1 on 2020-10-02 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaceapp', '0004_quizdb_live_img_bool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizdb_live',
            name='img',
        ),
        migrations.RemoveField(
            model_name='quizdb_live',
            name='img_bool',
        ),
    ]
