# Generated by Django 3.1.1 on 2020-10-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceapp', '0008_profile_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='default.jpg', null=True, upload_to='profilepic'),
        ),
    ]
