# Generated by Django 3.1.1 on 2020-10-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceapp', '0009_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='profilepic/default.jpg', null=True, upload_to='profilepic'),
        ),
    ]
