# Generated by Django 3.1.1 on 2020-10-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceapp', '0012_auto_20201003_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='myimg',
            field=models.ImageField(null=True, upload_to='profileimages\\'),
        ),
    ]
