# Generated by Django 3.1.1 on 2020-10-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceapp', '0013_auto_20201003_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='myimg',
            field=models.ImageField(default='default.jpg', null=True, upload_to='profileimages\\'),
        ),
    ]
