# Generated by Django 3.1.1 on 2020-10-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceapp', '0016_auto_20201004_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='myimg',
            field=models.ImageField(default='profileimages/default.jpg', null=True, upload_to='profileimages\\'),
        ),
    ]
