# Generated by Django 3.1.1 on 2020-10-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceapp', '0017_auto_20201004_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='child_name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
